version: '3.9'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"

  streaming-service:
    build: ./streaming-service
    ports:
      - "8082:8082"

